baseURL = 'https://blog.yskm.top/blog'
languageCode = 'zh'
title = '金屋'
theme = 'PaperMod'

sectionPageMenu = 'main'

[menu]
[[menu.main]]
  name = 'home'
  pageRef = '/'
  weight = 1
[[menu.main]]
  name = 'about'
  pageRef = '/about'
  weight = 10

[[menu.footer]]
  name = 'Term'
  pageRef = '/about'
